# Generated by Django 3.2.23 on 2024-01-03 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240102_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 1, 3)),
        ),
    ]
