# Generated by Django 3.2.23 on 2024-01-04 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_supplier_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(default='غير محدد', max_length=70)),
                ('date_created', models.DateField(default=datetime.date(2024, 1, 4))),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 1, 4)),
        ),
    ]
