# Generated by Django 3.2.23 on 2024-01-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_date_created_supplier_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='date_created',
            new_name='date',
        ),
    ]
