# Generated by Django 3.2.23 on 2024-01-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_container_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='num_items',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='num_not_sold_items',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='num_sold_items',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
