# Generated by Django 3.2.23 on 2024-01-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20240104_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='items',
            field=models.ManyToManyField(null=True, to='user.Item'),
        ),
    ]
