# Generated by Django 3.2.23 on 2024-01-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_container_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='type',
            field=models.CharField(default='عمولة', max_length=30),
        ),
    ]
