# Generated by Django 3.2.23 on 2024-01-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20240105_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
