# Generated by Django 3.2.23 on 2024-01-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_supplier_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='total',
        ),
    ]
