# Generated by Django 3.2.23 on 2024-01-05 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 5)),
        ),
    ]
