# Generated by Django 3.2.23 on 2024-01-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='items',
        ),
        migrations.CreateModel(
            name='ContainerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.container')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.item')),
            ],
        ),
    ]
