# Generated by Django 3.2.23 on 2024-01-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_supplier_num_of_containers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='num_of_containers',
        ),
        migrations.AddField(
            model_name='container',
            name='num_of_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
