# Generated by Django 3.2.23 on 2024-01-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20240105_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='num_of_items',
        ),
    ]
