# Generated by Django 3.2.23 on 2024-01-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_container_num_of_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='num_items',
        ),
    ]
