# Generated by Django 3.2.23 on 2024-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='containeritem',
            name='tool',
            field=models.CharField(default='صناديق', max_length=100),
        ),
    ]
