# Generated by Django 3.2.23 on 2024-01-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_container_main_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='con_weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
