# Generated by Django 3.2.23 on 2024-01-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_remove_container_con_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='containeritem',
            name='item_weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
