# Generated by Django 3.2.23 on 2024-01-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20240108_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
