# Generated by Django 3.2.23 on 2024-01-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_payment_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='rest',
        ),
    ]
