# Generated by Django 3.2.23 on 2024-01-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
