# Generated by Django 3.2.23 on 2024-01-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_lose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lose',
            name='forgive',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
