# Generated by Django 3.2.23 on 2024-01-09 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_alter_lose_forgive'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='carry',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='commission',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='tool_rent',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 9)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 9)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 9)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 9)),
        ),
    ]
