# Generated by Django 3.2.23 on 2024-01-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_auto_20240109_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='carry',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='commission',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='tool_rent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
