# Generated by Django 3.2.23 on 2024-01-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_auto_20240113_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='containeritem',
            name='remaining_count',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
