# Generated by Django 3.2.23 on 2024-01-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_containeritem_remaining_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='num_not_sold_items',
        ),
        migrations.RemoveField(
            model_name='container',
            name='num_sold_items',
        ),
    ]
