# Generated by Django 3.2.23 on 2024-01-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_auto_20240113_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='num_not_sold_items',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='num_sold_items',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
