# Generated by Django 3.2.23 on 2024-01-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_auto_20240113_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='num_not_sold_items',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='num_sold_items',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
