# Generated by Django 3.2.23 on 2024-01-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_auto_20240113_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='forgive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
