# Generated by Django 3.2.23 on 2024-01-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_payment_forgive'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='meal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15, null=True),
        ),
    ]
