# Generated by Django 3.2.23 on 2024-01-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_sale_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='rest',
        ),
    ]
