# Generated by Django 3.2.23 on 2024-01-14 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_remove_payment_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 14)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 14)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 14)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 14)),
        ),
    ]
