# Generated by Django 3.2.23 on 2024-01-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_payment_temp_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='temp_rest',
        ),
    ]
