# Generated by Django 3.2.23 on 2024-01-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_remove_payment_temp_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='temp_rest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
