# Generated by Django 3.2.23 on 2024-01-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_payment_temp_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='temp_rest',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True),
        ),
    ]
