# Generated by Django 3.2.23 on 2024-01-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_alter_payment_temp_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containeritem',
            name='remaining_count',
        ),
    ]
