# Generated by Django 3.2.23 on 2024-01-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_auto_20240114_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='carry',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='commission',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='tool_rent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
