# Generated by Django 3.2.23 on 2024-01-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_payment_temp_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='rest',
        ),
    ]
