# Generated by Django 3.2.23 on 2024-01-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_remove_payment_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='container_item',
        ),
        migrations.AddField(
            model_name='sale',
            name='container_items',
            field=models.ManyToManyField(to='user.ContainerItem'),
        ),
    ]
