# Generated by Django 3.2.23 on 2024-01-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_auto_20240116_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lose',
            name='forgive',
        ),
        migrations.RemoveField(
            model_name='lose',
            name='seller',
        ),
        migrations.AddField(
            model_name='lose',
            name='lose_type',
            field=models.CharField(default='غير معروف', max_length=30),
        ),
    ]
