# Generated by Django 3.2.23 on 2024-01-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_auto_20240116_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='container_item',
        ),
        migrations.AddField(
            model_name='sale',
            name='container_item',
            field=models.ManyToManyField(to='user.ContainerItem'),
        ),
    ]
