# Generated by Django 3.2.23 on 2024-01-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_auto_20240116_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='container',
        ),
        migrations.AddField(
            model_name='sale',
            name='container',
            field=models.ManyToManyField(to='user.Container'),
        ),
    ]
