# Generated by Django 3.2.23 on 2024-01-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_auto_20240116_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='container',
        ),
        migrations.AddField(
            model_name='sale',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.container'),
        ),
        migrations.RemoveField(
            model_name='sale',
            name='container_item',
        ),
        migrations.AddField(
            model_name='sale',
            name='container_item',
            field=models.ManyToManyField(to='user.ContainerItem'),
        ),
    ]
