# Generated by Django 3.2.23 on 2024-01-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0080_auto_20240116_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='his_money',
        ),
    ]
