# Generated by Django 3.2 on 2024-01-21 01:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0083_auto_20240119_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 21)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 21)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 21)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 21)),
        ),
        migrations.CreateModel(
            name='ContainerBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.PositiveIntegerField()),
                ('total_bill_row', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.container')),
                ('container_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.containeritem')),
            ],
        ),
    ]
