# Generated by Django 3.2.23 on 2024-01-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0088_recentaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentaction',
            old_name='action_type',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='recentaction',
            old_name='model_affected',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='recentaction',
            old_name='timestamp',
            new_name='time',
        ),
    ]
