# Generated by Django 3.2.23 on 2024-01-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0089_auto_20240124_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentAction',
        ),
    ]
