# Generated by Django 3.2.23 on 2024-01-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0090_delete_recentaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='bill_commission',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='main_commission',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
