# Generated by Django 3.2.23 on 2024-01-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0092_recentaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentAction',
        ),
    ]
