# Generated by Django 3.2.23 on 2024-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0094_recentaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentaction',
            name='old_model_affected',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
