# Generated by Django 3.2.23 on 2024-01-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0095_recentaction_old_model_affected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentaction',
            name='action_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recentaction',
            name='model_affected',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
