# Generated by Django 3.2.23 on 2024-01-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0096_auto_20240125_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentaction',
            name='old_model_affected',
        ),
    ]
