# Generated by Django 3.2.23 on 2024-01-27 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0098_sale_mortgage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='mortgage',
        ),
    ]
