# Generated by Django 3.2.23 on 2024-01-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0100_sale_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='total_dept',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
