# Generated by Django 3.2.23 on 2024-01-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0101_seller_total_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='total_dept',
        ),
    ]
