# Generated by Django 3.2.23 on 2024-01-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0102_remove_seller_total_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='dept',
        ),
    ]
