# Generated by Django 3.2.23 on 2024-01-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0104_auto_20240127_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='total_dept',
        ),
    ]
