# Generated by Django 3.2.23 on 2024-01-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0105_remove_seller_total_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containeritem',
            name='item_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
