# Generated by Django 3.2.23 on 2024-01-29 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0106_alter_containeritem_item_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.container'),
        ),
    ]
