# Generated by Django 3.2.23 on 2024-02-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0107_alter_sale_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='type',
        ),
    ]
