# Generated by Django 3.2 on 2024-02-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0108_remove_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentaction',
            name='action_sort',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
