# Generated by Django 3.2 on 2024-02-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0109_recentaction_action_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.supplier'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='container_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.containeritem'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.seller'),
        ),
    ]
