# Generated by Django 3.2 on 2024-02-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0110_auto_20240207_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='bill_commission',
        ),
        migrations.RemoveField(
            model_name='container',
            name='main_commission',
        ),
    ]
