# Generated by Django 3.2 on 2024-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0111_auto_20240207_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='bill_commission',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='main_commission',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
