# Generated by Django 3.2.23 on 2024-02-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0116_auto_20240214_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='type',
            field=models.CharField(default='عمولة', max_length=100),
        ),
        migrations.AlterField(
            model_name='containerexpense',
            name='expense_notes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='containerexpense',
            name='expense_type',
            field=models.CharField(default='غير معروف', max_length=100),
        ),
        migrations.AlterField(
            model_name='lose',
            name='lose_type',
            field=models.CharField(default='غير معروف', max_length=100),
        ),
        migrations.AlterField(
            model_name='recentaction',
            name='action_sort',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recentaction',
            name='action_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recentaction',
            name='model_affected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tool',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='place',
            field=models.CharField(default='غير محدد', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='place',
            field=models.CharField(default='غير محدد', max_length=100),
        ),
    ]
