# Generated by Django 3.2.23 on 2024-03-04 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0117_auto_20240214_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='container',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='containerbill',
            name='container',
        ),
        migrations.RemoveField(
            model_name='containerbill',
            name='container_item',
        ),
        migrations.RemoveField(
            model_name='containerexpense',
            name='container',
        ),
        migrations.RemoveField(
            model_name='containeritem',
            name='container',
        ),
        migrations.RemoveField(
            model_name='containeritem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Lose',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='recentaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='container',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='container_item',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='supplierpay',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='ContainerBill',
        ),
        migrations.DeleteModel(
            name='ContainerExpense',
        ),
        migrations.DeleteModel(
            name='ContainerItem',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='RecentAction',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierPay',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
