# Generated by Django 3.2 on 2024-03-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0121_alter_sale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='remain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
