# Generated by Django 3.2.23 on 2024-04-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0125_auto_20240406_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
