# Generated by Django 3.2.23 on 2024-04-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0128_lose'),
    ]

    operations = [
        migrations.AddField(
            model_name='lose',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lose',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
