# Generated by Django 3.2.23 on 2024-04-06 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0129_auto_20240406_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='sale_price',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='copies_num',
            new_name='sale_quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='paper_num',
        ),
        migrations.AddField(
            model_name='sale',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='crash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.item'),
        ),
    ]
