# Generated by Django 3.2.23 on 2024-04-06 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0131_remove_sale_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.item'),
        ),
    ]
