# Generated by Django 3.2.23 on 2024-04-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0132_sale_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
    ]
