# Generated by Django 3.2.23 on 2024-04-08 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0135_safe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date',
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.client'),
        ),
    ]
