# Generated by Django 3.2.23 on 2024-04-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0136_auto_20240408_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
