# Generated by Django 3.2.23 on 2024-04-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0138_auto_20240413_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('for_him', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
