# Generated by Django 3.2.23 on 2024-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0139_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='safe',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='method',
            field=models.CharField(choices=[('محفظة', 'محفظة'), ('نقدية', 'نقدية')], default='نقدية', max_length=100),
        ),
    ]
