# Generated by Django 3.2.23 on 2024-07-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0140_auto_20240416_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycome',
            name='payments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
